### Register user
POST http://localhost:8080/api/v1/authenticate/register
Content-Type: application/json

{
  "employeeName": "Ivo",
  "employeeSurname": "Ivic",
  "employeeEmail": "Ivo@gmail.com",
  "employeePassword": "1234",
  "employeeRole": "EMPLOYEE"
}

> {% client.global.set("auth-token", response.body.access_token) %}


### Change password
PATCH http://localhost:8080/api/v1/employees/changePassword
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "oldPassword": "1234",
  "newPassword": "9876",
  "passwordConfirmation": "9876"
}

### Login again and update the token
POST http://localhost:8080/api/v1/authenticate/login
Content-Type: application/json

{
  "employeeEmail": "Ivo@gmail.com",
  "employeePassword": "9876"
}

> {% client.global.set("new-auth-token", response.body.access_token) %}

### Query the Employee controler after password change
GET http://localhost:8080/api/v1/employees/landing
Authorization: Bearer {{new-auth-token}}
